server:
  port: 8090
spring:
  profiles:
#    激活application-xxx.yml配置文件
    active: dev
#    active: prod
file:
  fileDirectory: D:/Projects/ActualProjects/experiment-ai/lesson/
  userExperimentDirectory: D:/Projects/ActualProjects/experiment-ai/user/
  fileRequestUrl: http://localhost:4040/
#file:
#  fileDirectory: /home/project/experiment-ai/file/
#  fileDirectory: /home/projects/experiment-ai/file/
#  fileRequestUrl: http://124.221.34.158:4040/
#  fileRequestUrl: http://10.0.3.67:4040/
jupyter:
  expUrl: http://localhost:8888/notebooks/
#  expUrl: http://124.221.34.158:8888/
#  expUrl: http://10.0.3.67:8888/notebooks/
logging:
  level:
    root: info