server:
  port: 8089
spring:
  profiles:
#    激活application-dao.yml配置文件
    active: dao
avatar:
  image: http://10.0.7.205:8081/img.jpg
file:
  address: http://localhost:8081/
  fileDirectory: D:/Projects/ActualProjects/experiment-ai/file/
jupyter:
  expUrl: http://10.0.7.205:8888/notebooks/
#file:
#  address: http://localhost
#  filePath: /home/pl/files/
logging:
  level:
    root: info