server:
  port: 8090
spring:
  profiles:
#    激活application-xxx.yml配置文件
    active: dev
#    active: prod
avatar:
  image: http://10.0.7.205:8081/img.jpg
file:
  fileDirectory: D:/Projects/ActualProjects/experiment-ai/file/
  fileRequestUrl: http://localhost:4040/
#file:
#  fileDirectory: /home/experiment/file
#  fileRequestUrl: http://localhost:4040/
jupyter:
  expUrl: http://localhost:8888/
#file:
#  address: http://localhost
#  filePath: /home/pl/files/
logging:
  level:
    root: info