server:
  port: 8090
spring:
  profiles:
#    激活application-xxx.yml配置文件
    active: dev
#    active: prod
file:
  fileDirectory: D:/Projects/ActualProjects/experiment-ai/file/
  fileRequestUrl: http://localhost:4040/
#file:
#  fileDirectory: /home/project/experiment-ai/file/
#  fileRequestUrl: http://124.221.34.158:4040/
jupyter:
#  expUrl: http://localhost:8888/
  expUrl: http://124.221.34.158:8888/
logging:
  level:
    root: info